trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:
- checkout: self
  clean: true
  submodules: true
    
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  
- task: DownloadSecureFile@1
  displayName: 'Download MSAL credentials'
  name: CredentialSecureFile
  inputs:
    secureFile: MsalClientID.txt

- task: CopyFiles@2
  displayName: 'Copy MSAL credentials'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '$(CredentialSecureFile.secureFilePath)'
    TargetFolder: '$(Build.SourcesDirectory)\Emerald.App\Emerald.App'

- task: VSBuild@1
  inputs:
    platform: '$(buildPlatform)'
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload'
